Added $lanify
coffincw/UMass-STEM-Discord-Bot pull request #29
Opened 2020-04-07 04:30 UTC by AardeYamz

Added $lanify using image placed in the meme folder, still using tim_scale

2020-04-07 04:32 UTC, coffincw commented
Hi Yannis,

Can you pull from master to your fork so that you have the most up to date code?  And this can be merged easily

2020-04-07 04:36 UTC, AardeYamz commented
I believe that I have done that just now.

2020-04-07 05:17 UTC, AardeYamz commented
Added additional features and aliases

2020-04-07 15:00 UTC, coffincw requested changes
Looks good, just need to make a few adjustments.

2020-04-07 15:00 UTC, coffincw commented on src/bot.py
> +    await ify(ctx, tim_scale, 'memes/lan/lan-face.png', 'lan-face.png', args)
Does not work, functions and variables from other files need to be referenced. Should be:
```suggestion
    await custom_meme.ify(ctx, face_detection.lan_scale, 'memes/lan/lan-face.png', 'lan-face.png', args)
```
Also please add this scale underneath `tim_scale` in _face_detection.py_
`lan_scale = (1.55, 0.45, 0.4)`

2020-04-07 15:00 UTC, coffincw commented on src/bot.py
> +@client.command(name='zoommarius', aliases=['streamermarius', 'zoom-marr', 'zoom-mar', 'zoom-marius'])
```suggestion
@client.command(name='zoommar', aliases=['streamermarius', 'zoommarius', 'zoom-marr', 'zoom-mar', 'zoom-marius'])
```

2020-04-07 15:00 UTC, coffincw commented on src/bot.py
> +@client.command(name='zoommarun', aliases=['streamerarun', 'zoom-arun', 'zoom-adunna', 'zoomadunna'])
```suggestion
@client.command(name='zoomarun', aliases=['streamerarun', 'zoom-arun', 'zoom-adunna', 'zoomadunna'])
```

2020-04-07 15:00 UTC, coffincw commented on src/bot.py
> +async def zoommarius(ctx, *args):
```suggestion
async def zoomarun(ctx, *args):
```
duplicate function name

2020-04-07 15:00 UTC, coffincw commented on src/bot.py
> +        '*zoommarius [image/url]*': 'Pastes an image of marius from Zoom onto the given image in the top right corner',
```suggestion
        '*zoommar [image/url]*': 'Pastes an image of marius from Zoom onto the given image in the top right corner',
```

2020-04-08 04:20 UTC, AardeYamz commented
Made suggested modifications

2020-04-08 04:58 UTC, coffincw approved these changes
Looks good!

2020-04-08 04:59 UTC, merged